db::PostgreSQL(DATABASE "argos_test", USER "ianrose", PASSWORD "ianrose");

Script(write db.insert test mystr=ok myint=1,
       wait 1,
       print "--------------------------",
       write db.insert test mystr=foo myint=65 myreal=99,
       wait 1,
       print "--------------------------",
       write db.insert test mystr=foo myint=65 myreal=99.324,
       wait 1,
       print "--------------------------",
       write db.insert test mystr="this is a phrase" myint=56,
       wait 1,
       print "--------------------------",
       write db.insert test mystr=foo myint=65.7,
       wait 1,
       print "--------------------------",
       write db.insert test mystr=ok myint=1,
       wait 1,
       print "--------------------------",
       write db.insert test mystr=foo myint=chicken,
       wait 1,
       print "--------------------------",
       write db.insert test mystr=ok myint=1,
       wait 1,
       print "--------------------------",
       write db.insert test,
       wait 1,
       print "--------------------------",
       write db.insert test mystr=ok myint=1,
       wait 1,
       print "--------------------------",
       write db.insert test mystr="some stuff" myreal=75.001,
       stop);
